export const LAYOUT_CONSTANTS = {
  OVAL_RADIUS_X: 150,
  MIN_RADIUS_Y: 100,
  MAX_RADIUS_Y: 250,
  RADIUS_Y_SCALE_FACTOR: 15,
  CENTER_X: 300,
  MIN_CENTER_Y: 200,
  MAX_CENTER_Y: 400,
  CENTER_Y_BASE: 150,
  CENTER_Y_SCALE_FACTOR: 8,
  MAX_TOTAL_SPREAD: Math.PI * 0.4, // 72 degrees
  MIN_SPACING: Math.PI * 0.08,
  ARC_CENTER: Math.PI,
  AGGREGATOR_X_OFFSET: 200,
  UNIFIED_X_OFFSET: 150,
  AGGREGATOR_SPACING_FRACTION: 0.5,
  MIN_AGGREGATOR_SPACING: 12,
  UNIFIED_SPACING: 80
};

export const NODE_SIZE_CONSTANTS = {
  PRIMARY_MIN_SIZE: 8,
  PRIMARY_MAX_SIZE: 35,
  PRIMARY_SCALE_DIVISOR: 100000,
  PRIMARY_SCALE_MULTIPLIER: 3,
  PRIMARY_BASE_SIZE: 8,
  UNIFIED_MIN_SIZE: 60,
  UNIFIED_MAX_SIZE: 100,
  UNIFIED_SCALE_DIVISOR: 1000000,
  UNIFIED_SCALE_MULTIPLIER: 0.8,
  UNIFIED_BASE_SIZE: 60,
  AGGREGATOR_MIN_SIZE: 45,
  AGGREGATOR_MAX_SIZE: 80,
  AGGREGATOR_SCALE_DIVISOR: 1000000,
  AGGREGATOR_SCALE_MULTIPLIER: 0.6,
  AGGREGATOR_BASE_SIZE: 45
};

export const HEIGHT_CONSTANTS = {
  BASE_HEIGHT: 300,      // Minimum height for 1 source
  MAX_HEIGHT: 900,       // Target height for 25 sources
  MAX_SOURCES: 25        // Reference point for maximum scaling
};

export const COLORS = {
  PRIMARY_NODE: '#88C0D0',
  PRIMARY_LABEL: '#333',
  NON_PRIMARY_LABEL: '#fff',
  DEFAULT_EDGE: 'rgba(157, 121, 214, 0.6)' // Default purple edge color
};

export const EDGE_CONSTANTS = {
  AGGREGATOR_ALPHA: 0.5, // 50% transparency for aggregator-colored edges
  DEFAULT_ALPHA: 0.6     // Default edge transparency
};