# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "network_name" {}
variable "k8s_subnetwork" {}
variable "k8s_pod_ip_range" {}
variable "k8s_svc_ip_range" {}
variable "k8s_secrets" {
  sensitive = true
  type      = map(string)
}
