# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "google" {
  project               = "mtrx-hub-dev-3of"
  user_project_override = true
  billing_project       = "core-422020"
}
provider "google-beta" {
  project               = "mtrx-hub-dev-3of"
  user_project_override = true
  billing_project       = "core-422020"
}
