# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "google" {
  project = "mtrx-hub-dev-3of"
  billing_project       = "core-422020"
}
provider "google-beta" {
  project = "mtrx-hub-dev-3of"
  billing_project       = "core-422020"
}
