from enum import StrEnum


class ApprovalStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    APPROVED = "APPROVED"
    DISCONTINUED = "DISCONTINUED"
    NOT_APPROVED = "NOT APPROVED"


class MarketingStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    RX = "RX"
    OTC = "OTC"
    DISCONTINUED = "DISCONTINUED"
    RX_DISCONTINUED = "RX; DISCONTINUED"
    DISCONTINUED_RX = "DISCONTINUED; RX"
    OTC_RX = "OTC; RX"
    RX_OTC = "RX; OTC"
    DISCONTINUED_OTC = "DISCONTINUED; OTC"
    OTC_DISCONTINUED = "OTC; DISCONTINUED"
    RX_DISCONTINUED_OTC = "RX; DISCONTINUED; OTC"
    AUTHORISED = "AUTHORISED"
    WITHDRAWN = "WITHDRAWN"
    NOT_AUTHORISED = "NOT AUTHORISED"
    REFUSED = "REFUSED"
    AUTHORISED_REFUSED = "AUTHORISED; REFUSED"
    AUTHORISED_WITHDRAWN = "AUTHORISED; WITHDRAWN"
    AUTHORISED_WITHDRAWN_REFUSED = "AUTHORISED; WITHDRAWN; REFUSED"
    WITHDRAWN_AUTHORISED = "WITHDRAWN; AUTHORISED"
