# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "org_id" {}
variable "billing_account" {}
variable "default_region" {}
variable "super_admins" {}
variable "project_id" {}
variable "billing_project" {}
variable "storage_bucket_name" {}
variable "environment" {}
