# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "org_id" {}
variable "billing_account" {}
variable "default_region" {}
variable "super_admins" {}
variable "environment" {}
variable "repo_revision" {}
variable "project_id" {}
variable "billing_project" {}
variable "storage_bucket_name" {}
variable "network_name" {}
variable "k8s_subnetwork" {}
variable "k8s_pod_ip_range" {}
variable "k8s_svc_ip_range" {}
variable "gitops_repo_url" {}
variable "gitops_repo_creds" {}
variable "k8s_secrets" {
  sensitive = true
  type      = map(string)
}
