gds.enterprise.license_file=/license/lic.txt
server.memory.pagecache.size=512M
server.default_listen_address=0.0.0.0
server.routing.advertised_address=4cbab19bc279:7688
server.directories.plugins=/plugins
server.directories.logs=/logs
dbms.security.procedures.whitelist=gds.*, apoc.*

server.discovery.advertised_address=a926b94861d3:5000

server.cluster.advertised_address=a926b94861d3:6000

server.cluster.raft.advertised_address=a926b94861d3:7000
